// Map the radical names stored in Kanji.radicals (WaniKani-style English
// labels) to their canonical Unicode glyph. Only includes mappings we are
// confident about; mnemonic-only WaniKani names that don't correspond to a
// standard Kangxi radical (Viking, Geoduck, Narwhal, Triceratops, Yurt,
// Mustache, Lion, Alligator, Lip Ring, …) are intentionally omitted so the
// UI falls back to showing just the name rather than the wrong character.
export const RADICAL_GLYPHS: Record<string, string> = {
  // people / body
  Person: "人",
  Child: "子",
  Woman: "女",
  Mother: "母",
  Mama: "母",
  Father: "父",
  Hand: "手",
  Heart: "心",
  Eye: "目",
  Ear: "耳",
  Mouth: "口",
  Tongue: "舌",
  Toe: "止",
  Legs: "儿",
  Head: "頁",
  Self: "自",
  Life: "生",

  // nature
  Sun: "日",
  Moon: "月",
  Fire: "火",
  Water: "水",
  Rain: "雨",
  River: "川",
  Mountain: "山",
  Tree: "木",
  Leaf: "葉",
  Rice: "米",
  "Rice Paddy": "田",
  Stone: "石",
  Gold: "金",
  Dirt: "土",
  Heaven: "天",
  Ground: "土",
  Wind: "風",
  Sound: "音",

  // animals
  Cow: "牛",
  Sheep: "羊",
  Insect: "虫",
  Shellfish: "貝",
  Fins: "魚",

  // tools / objects
  Knife: "刀",
  Sword: "刀",
  Axe: "斤",
  Bow: "弓",
  Brush: "聿",
  Car: "車",
  Gate: "門",
  Lid: "亠",
  Cross: "十",
  Tent: "巾",
  Stool: "几",
  Spoon: "匕",
  Umbrella: "亼",
  Coffin: "匚",
  Window: "囧",
  Book: "本",
  Key: "鍵",

  // qualities / abstract
  Big: "大",
  Small: "小",
  White: "白",
  Long: "長",
  Heavy: "重",
  Correct: "正",
  Not: "不",
  Middle: "中",
  King: "王",
  Master: "主",
  Private: "厶",
  Power: "力",
  Energy: "気",
  Spirit: "気",
  Stand: "立",
  Direction: "方",
  West: "西",
  Winter: "冬",
  Easy: "易",
  Dry: "干",
  Temple: "寺",
  Village: "里",
  Construction: "工",
  Now: "今",
  Meet: "会",
  See: "見",
  Say: "言",
  Sell: "売",
  Eat: "食",
  Go: "行",
  Enter: "入",
  Loiter: "彳",
  Beforehand: "予",

  // numbers
  Two: "二",
  Five: "五",
  Seven: "七",
  Nine: "九",
  Thousand: "千",

  // particles / drops
  Drop: "丶",
  Horns: "丷",
};
